export const ADD_ROOM_STAY = 'ADD_ROOM_STAY'
export const UPDATE_ROOM_STAY = 'UPDATE_ROOM_STAY'
export const REMOVE_ROOM_STAY = 'REMOVE_ROOM_STAY'

export const ADD_COURSE = 'ADD_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'

export const ADD_TTC_STAY = 'ADD_TTC_STAY'

export const UPDATE_GUESTS = 'UPDATE_GUESTS'

export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'